language: python
python:
  - "2.7"
# command to install dependencies
# install: "pip install -r requirements.txt --use-mirrors"
install: "pip install Sphinx"
# command to run tests
script: sphinx-build -b html -d _build/doctrees   . _build/html
